version: "3.5"
services:
  centos7igbinaryphp74:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        image: php-apcu-7.4
  centos8igbinaryphp74:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: 8
        image: php-apcu-7.4

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8